---
- name: Get Device Facts
  hosts: all
  roles:
  connection: local
  gather_facts: no

  tasks:
  - name: Retrieve information from devices running Junos OS
    junos_facts:
      host={{ inventory_hostname }}
      port={{ ansible_ssh_port }}
    register: junos
