---
- name: Get Device config
  hosts: all
  roles:
  connection: local
  gather_facts: no

  tasks:
  - junos_get_config:
      host: "{{ inventory_hostname }}"
      dest: "{{ inventory_hostname }}.xml"
      format: xml
      options: {inherit: inherit, groups: groups}
