---
- name: Get Device config
  hosts: all
  roles:
  connection: local
  gather_facts: no

  tasks:
  - name: get config
    junos_get_config:
      host: "{{ inventory_hostname }}"
      format: xml
      dest: "{{ inventory_hostname }}.xml"
