---
- name: Get Device config
  hosts: all
  roles:
  connection: local
  gather_facts: no

  tasks:
  - name: Execute single show version command.
      juniper_junos_command:
      commands:
        - "show version"
      register: response
